# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - actions/*
      docker:
        patterns:
          - docker/*
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime:
        patterns:
          - ws
      dev-common:
        patterns:
          - '@eslint/*'
          - '@types/*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - '@vitest/*'
          - eslint
          - typescript
          - vitest
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
      - dependency-name: 'typescript'
        update-types:
          - version-update:semver-major
